language: java
jdk:
  - openjdk7
  - oraclejdk7
addons:
  firefox: "28.0"
install:
- wget -qO- https://toolbelt.heroku.com/install-ubuntu.sh | sh
- heroku plugins:install https://github.com/ddollar/heroku-push
script:
- ./gradlew check
- heroku push --app higgees-stage
- ./gradlew seleniumXvfb
deploy:
  provider: heroku
  api_key: a2d549b2-bd8a-48c0-9fb6-561d465dc112
  app: higgees
  on: master 
notifications:
  email:
    recipients:
      - gunnarkp13@ru.is
      - stefand12@ru.is
      - gudjon12@ru.is
      - ingvi10@ru.is
      - egillj13@ru.is
      - hrannar10@ru.is
      - einara12@ru.is
    on_success: change
    on_failure: always
# http://docs.travis-ci.com/user/build-configuration/
