language: java
jdk:
  - openjdk7
addons:
  firefox: "28.0"
deploy:
  provider: heroku
  api_key: "c167572d-edbc-4061-9921-fc81b439f28f"
  app: "tictactoe-assignment"
  strategy: git 
after_script:
  - ./gradlew
  - ./gradlew seleniumXvfb


notifications:
  email:
    recipients:
      - gunnarkp13@ru.is
      - stefand12@ru.is
      - gudjon12@ru.is
      - ingvi10@ru.is
      - egillj13@ru.is
      - hrannar10@ru.is
      - einara12@ru.is
    on_success: change
    on_failure: always
# http://docs.travis-ci.com/user/build-configuration/
